# Generated by Django 4.1.7 on 2023-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0002_partido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='patidos_jugados',
            new_name='partidos_jugados',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_visitante',
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local_esperados',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante_esperados',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='partido',
            name='hora',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='marcador',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
