# Generated by Django 4.1.7 on 2023-02-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0003_rename_patidos_jugados_equipo_partidos_jugados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='hora',
        ),
    ]
