# Generated by Django 4.1.7 on 2023-02-19 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0006_alter_partido_goles_local_esperados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_local', to='tracker_liga.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipo_visitante', to='tracker_liga.equipo'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local_esperados',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante_esperados',
            field=models.FloatField(default=0.0),
        ),
    ]
