# Generated by Django 4.1.7 on 2023-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0008_alter_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_ganados',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='partidos_perdidos',
        ),
        migrations.AddField(
            model_name='equipo',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='edad_media',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_favor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='posesion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tarjeta_amarilla',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tarjeta_roja',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
    ]
