# Generated by Django 4.1.7 on 2023-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0009_remove_equipo_partidos_ganados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='asistencias_partido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='conducciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_esperados',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_esperados_partido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='goles_partido',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipo',
            name='pases_progresivos',
            field=models.IntegerField(default=0),
        ),
    ]
