# Generated by Django 4.1.7 on 2023-02-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0010_equipo_asistencias_partido_equipo_conducciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='genero',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='equipo',
            name='liga',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
