# Generated by Django 4.1.7 on 2023-03-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0011_equipo_fecha_equipo_genero_equipo_liga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfrentamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='null', max_length=50)),
                ('goles_favor', models.CharField(default='null', max_length=50)),
                ('goles_contra', models.CharField(default='null', max_length=50)),
                ('adversario', models.CharField(default='null', max_length=50)),
                ('goles_esperados_favor', models.CharField(default='null', max_length=50)),
                ('goles_esperados_contra', models.CharField(default='null', max_length=50)),
                ('posesion', models.CharField(default='null', max_length=50)),
                ('fecha', models.CharField(default='null', max_length=50)),
                ('liga', models.CharField(default='null', max_length=50)),
                ('genero', models.CharField(default='null', max_length=50)),
                ('equipo', models.CharField(default='null', max_length=50)),
            ],
        ),
    ]
