# Generated by Django 4.1.7 on 2023-03-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_liga', '0012_enfrentamientos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enfrentamientos',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='marcador',
            new_name='FTAG',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_local_esperados',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='goles_visitante_esperados',
        ),
        migrations.AddField(
            model_name='partido',
            name='FTHG',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='FTR',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='HTAG',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='HTHG',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='HTR',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='fecha',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='partido',
            name='temporada',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
